config/routes.rb
Rails.application.routes.draw do

  resources :users, only: [:new, :create, :show] do
    resources :ledgers, shallow: true do
      resources :transactions
    end
  end

  resources :sessions, only: [:new, :create, :delete]

end

app/models/ledger.rb
class Ledger < ActiveRecord::Base
  belongs_to :user
  has_many :out_transactions, foreign_key: "sender_id"
  has_many :in_transactions, foreign_key: "receiver_id"

  monetize :amount_cents

  validates :name, presence: true

  def transactions
    Transaction.where('sender_id = ? OR receiver_id = ?', id, id).order(:created_at).reverse_order
  end

end

app/models/session.rb
require 'securerandom'

class Session < ActiveRecord::Base
  attr_accessor :email, :password

  belongs_to :user

  validates :user, presence: true
  validates :cookie_hash, presence: true

  before_validation do
    if self.email && self.password
      self.user = User.login(self.email, self.password) || nil
    end

    self.cookie_hash = SecureRandom.base64
  end
end

app/models/transaction.rb
class Transaction < ActiveRecord::Base
  belongs_to :sender, class_name: "Ledger", :inverse_of => :out_transactions
  belongs_to :receiver, class_name: "Ledger", :inverse_of => :in_transactions

  validates :sender, presence: true
  validates :receiver, presence: true

  monetize :amount_cents

  after_create do
    self.sender.update_attribute :amount, self.sender.amount - self.amount
    self.receiver.update_attribute :amount, self.receiver.amount + self.amount
  end

  after_destroy do
    self.sender.update_attribute :amount, self.sender.amount + self.amount
    self.receiver.update_attribute :amount, self.receiver.amount - self.amount
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  has_many :ledgers

  validates :name, uniqueness: {lowercase: false}, presence: true
  validates :email, uniqueness: {lowercase: false}, presence: true

  def self.login email, password
    User.find_by_email(email).try(:authenticate, password)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include UserHelper

  private

  def require_login
    if not logged_in?
      session[:after_login_action] = request.path
      redirect_to new_session_path
    end
  end
end

app/controllers/ledgers_controller.rb
class LedgersController < ApplicationController
  before_filter :require_login
  before_filter :load_user

  def new
    @ledger = current_user.ledgers.build
  end

  def create
    @ledger = current_user.ledgers.build new_ledger_params

    if @ledger.save
      redirect_to @ledger
    else
      render :new
    end
  end

  def show
    @ledger = Ledger.find(params[:id])
  end

  def edit
  end

  def update
  end

  def index
    @ledgers = @user.ledgers
  end

  def delete
  end

  private

  def load_user
    @user = User.find params[:user_id]
  end

  def new_ledger_params
    params.require(:ledger).permit(:name, :description, :amount_currency)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @session = Session.new
  end

  def create
    @session = Session.new new_session_params

    if @session.save then
      cookies[:session] = @session.cookie_hash
      redirect_to session.delete(:after_login_action) { @session.user }
    else
      render :new
    end
  end

  def delete
  end

  private

  def new_session_params
    params.require(:session).permit(:email, :password)
  end

end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_filter :require_login
  before_filter :load_ledger

  def new
    @transaction = @ledger.transactions.build
  end

  def create
    @transaction = @ledger.transactions.build new_transaction_params

    if @transaction.save then
      redirect_to @ledger
    else
      render :new
    end
  end

  def edit
  end

  def update
  end

  def index
  end

  def delete
  end

  def show
  end

  private

  def load_ledger
    @ledger = Ledger.find(params[:ledger_id])
  end

  def new_transaction_params
    params.require(:transaction).permit(:name, :description, :amount, :amount_currency, :sender_id, :receiver_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new new_user_params

    if @user.save
      redirect_to @user
    else
      render :new
    end
  end

  def show
  end

  private

  def new_user_params
    params.require(:user).permit(:name, :public_key, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ledgers_helper.rb
module LedgersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/helpers/user_helper.rb
module UserHelper
  def current_user
    if cookies[:session]
      s = Session.find_by_cookie_hash(cookies[:session])
      @_current_user ||= (s && s.user)
    end
    @_current_user
  end

  def logged_in?
    !!current_user
  end
end

app/views/layouts/application.html.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:charset => "utf-8"}/
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %title= content_for?(:title) ? yield(:title) : "foundation-rails"
    = stylesheet_link_tag    "application"
    = javascript_include_tag "vendor/modernizr"
    = javascript_include_tag "application", 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = yield

app/views/ledgers/_ledger.html.haml
%div{:class => "row"}

  %div{:class => "small-10 medium-10 large-10 columns"}

    %div{:class => "row"}
      %div{:class => "small-5 medium-5 large-5 columns"}
        = link_to ledger.name, ledger

      %div{:class => "small-5 medium-5 large-5 columns text-right"}
        = ledger.amount

      %div{:class => "small-2 medium-2 large-2 columns"}
        = ledger.amount_currency

    %div{:class => "row"}
      %div{:class => "small-12 medium-12 large-12 columns"}
        <!-- Space for buttons like "New transaction and so on -->

  %div{:class => "small-2 medium-2 large-2 columns"}
    <!-- Space for buttons like "New transaction and so on -->

app/views/ledgers/create.html.haml
%h1 Ledgers#create
%p Find me in app/views/ledgers/create.html.haml

app/views/ledgers/delete.html.haml
%h1 Ledgers#delete
%p Find me in app/views/ledgers/delete.html.haml

app/views/ledgers/edit.html.haml
%h1 Ledgers#edit
%p Find me in app/views/ledgers/edit.html.haml

app/views/ledgers/index.html.haml
%h1= current_user.name + ": Ledgers"

%div{:class => "panel"}
  <!-- Here go configurations for the ledgers to show -->

%div{:class => "panel"}
  - @ledgers.each do |l|
    = render l

app/views/ledgers/new.html.haml
= form_for @ledger do |f|
  = f.text_field :name
  = f.text_field :description
  = f.text_field :amount_currency
  = f.submit

app/views/ledgers/show.html.haml
%h2= @ledger.name

%p
  Money:
  = humanized_money_with_symbol @ledger.amount

%p
  = link_to "New Transaction", new_ledger_transaction_path(@ledger)

%ul
  - @ledger.transactions.each do |tr|
    %li
      %strong= tr.name
      %span= tr.amount
      %span= if tr.sender == @ledger then "-> Out to" else "<- From " end
      %span= if tr.sender == @ledger then tr.receiver.name else tr.sender.name end

app/views/ledgers/update.html.haml
%h1 Ledgers#update
%p Find me in app/views/ledgers/update.html.haml

app/views/transactions/create.html.haml
%h1 Transactions#create
%p Find me in app/views/transactions/create.html.haml

app/views/transactions/delete.html.haml
%h1 Transactions#delete
%p Find me in app/views/transactions/delete.html.haml

app/views/transactions/edit.html.haml
%h1 Transactions#edit
%p Find me in app/views/transactions/edit.html.haml

app/views/transactions/index.html.haml
%h1 Transactions#index
%p Find me in app/views/transactions/index.html.haml

app/views/transactions/new.html.haml
= form_for [@ledger,@transaction] do |f|
  = f.text_field :name
  = f.text_field :description
  = f.text_field :sender_id
  = f.text_field :receiver_id
  = f.text_field :amount
  = f.text_field :amount_currency
  = f.submit

= @transaction.errors.full_messages

app/views/transactions/show.html.haml
%h1 Transactions#show
%p Find me in app/views/transactions/show.html.haml

app/views/transactions/update.html.haml
%h1 Transactions#update
%p Find me in app/views/transactions/update.html.haml

app/views/users/create.html.haml
%h1
  User#create

%p
  Find me in app/views/user/create.html.erb

app/views/users/new.html.haml
= form_for @user do |f|
  = f.text_field :name
  = f.text_field :email
  = f.text_field :public_key
  = f.password_field :password
  = f.submit

app/views/users/show.html.haml
%h1
  User#show

%p
  Find me in app/views/user/show.html.erb

- if logged_in?
  %h2
    You are logged in!
- else
  Please
  = link_to "login", new_session_path